import type { NextPage } from "next";
import Head from "next/head";

type IndexPageProps = () => {};

const IndexPage: NextPage<IndexPageProps> = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Index page</div>
    </>
  );
};

export default IndexPage;
