import type { NextPage } from "next";
import Head from "next/head";
import { Header } from '../components/Header';

type IndexPageProps = () => {};

const IndexPage: NextPage<IndexPageProps> = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header title={"Where in the world?"} theme={"Dark mode"} />
    </>
  );
};

export default IndexPage;
